theme: jekyll-theme-minimal
title: CompSci 390 Spring 2021
description: Programming Languages Paradigms
layouts_dir: .internal/layouts
include: ['.internal']
moodle: https://moodle.rose-hulman.edu/course/view.php?id=65273
